consumes:
  - application/json-patch+json
  - application/merge-patch+json
  - application/strategic-merge-patch+json
  - application/apply-patch+yaml
description: partially update status of the specified HorizontalPodAutoscaler
x-kab-description-zh: 部分更新指定的 HorizontalPodAutoscaler 对象的状态（status）
operationId: patchAutoscalingV2NamespacedHorizontalPodAutoscalerStatus
parameters:
  - in: body
    name: body
    required: true
    schema:
      $ref: '#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Patch'
  - $ref: '#/parameters/dryRun'
  - $ref: '#/parameters/fieldManagerPatch'
  - $ref: '#/parameters/fieldValidation'
  - $ref: '#/parameters/force'
  - description: name of the HorizontalPodAutoscaler
    x-kab-description-zh: HorizontalPodAutoscaler 的名称
    in: path
    name: name
    required: true
    type: string
    uniqueItems: true
  - $ref: '#/parameters/namespace'
  - $ref: '#/parameters/pretty'
path: 
  /apis/autoscaling/v2/namespaces/{namespace}/horizontalpodautoscalers/{name}/status
produces:
  - application/json
  - application/yaml
  - application/vnd.kubernetes.protobuf
responses:
  '200':
    description:  OK
    x-kab-description-zh: 成功
    schema:
      $ref: '#/definitions/io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler.GET'
  '201':
    description:  Updated
    x-kab-description-zh: 已更新
    schema:
      $ref: '#/definitions/io.k8s.api.autoscaling.v2.HorizontalPodAutoscaler.GET'
  '401':
    description:  Unauthorized
    x-kab-description-zh: 未授权操作
schemes:
  - https
tags:
  - autoscaling_v2
verb: patch
x-kubernetes-action: patch
x-kubernetes-group-version-kind:
  group: autoscaling
  kind: HorizontalPodAutoscaler
  version: v2

